version: '3'
services:
  node:
    container_name: node
    image: very-haunted:node
    entrypoint: npm run watch
    expose:
      - 3000
    ports:
      - '3000:3000'
    env_file:
      - ./app/.env
    volumes:
      - ./app:/srv
    working_dir: /srv
