version: '3'
services:
  node:
    container_name: nestjs
    image: very-haunted:node
    entrypoint: node app.js
    depends_on:
      - postgres
    expose:
      - 3000
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/srv
    working_dir: /srv

  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    #    volumes:
    #      - data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "nakama" ]
      interval: 3s
      timeout: 3s
      retries: 5

  nakama:
    container_name: nakama-init
    image: registry.heroiclabs.com/heroiclabs/nakama:3.20.1-arm
    links:
      - "postgres:db"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama
