version: '3'
services:
  node:
    container_name: node
    image: very-haunted:node
    entrypoint: npm start
    depends_on:
      - postgres
    expose:
      - 3000
    ports:
      - '3000:3000'
    env_file:
      - ./src/.env
    volumes:
      - ./src:/srv
    working_dir: /srv
